package cloud.trotter.dashbuddy.core.database.analytics

data class TimeConstantRow(
    val platform: String,
    val eventSequenceId: Long,
    val phaseStartedAt: Long,
    val arrivedAt: Long?,
    val completedAt: Long,
    val sessionId: String?,
    val sessionAssigned: Int,
    val payBasis: String,
    val originalPayBasis: String?,
    val realizedMinutes: Double?,
    val milesToStore: Double?,
    val milesToDropoff: Double?,
    val odometerAtArrival: Double?,
    val pickupOdometerAtConfirmation: Double?,
    val jobOfferCount: Int?,
    val soleOfferHash: String?,
    val orderCount: Int?,
    val orderCountProven: Boolean?,
    val isShop: Boolean?,
    val offerOutcomeResolved: String?,
    val deliveryCount: Int,
    val pickupCount: Int,
    val acceptedOfferCount: Int,
    val matchingOfferCount: Int,
    val offerDecidedAt: Long?,
    val pickupPhaseStartedAt: Long?,
    val pickupArrivedAt: Long?,
    val pickupConfirmedAt: Long?,
    val pickupActivity: String?,
)
