package cloud.trotter.dashbuddy.pipeline.recognition.matchers

import cloud.trotter.dashbuddy.data.dash.DashType
import cloud.trotter.dashbuddy.pipeline.recognition.Screen
import cloud.trotter.dashbuddy.pipeline.recognition.ScreenInfo
import cloud.trotter.dashbuddy.test.LogToUiNodeParser
import org.junit.Assert.*
import org.junit.Test

class IdleMapMatcherTest {

    private val matcher = IdleMapMatcher()

    // Log from 2026-01-07 21:31:13.566
    // Scenario 1: User is idle, but zone is gray/busy.
    // Button says "Claim a spot" or "Schedule", NOT "Dash".
    private val zoneBusyLog = """
UiNode(, id=no_id, state=null, class=android.widget.FrameLayout)
  UiNode(, id=no_id, state=null, class=android.widget.LinearLayout)
    UiNode(, id=no_id, state=null, class=android.widget.FrameLayout)
      UiNode(, id=action_bar_root, state=null, class=android.widget.LinearLayout)
        UiNode(, id=content, state=null, class=android.widget.FrameLayout)
          UiNode(, id=overlay_gesture_manager, state=null, class=android.widget.FrameLayout)
            UiNode(, id=root_constraint_layout, state=null, class=android.view.ViewGroup)
              UiNode(, id=side_nav_content_container, state=null, class=android.widget.FrameLayout)
                UiNode(, id=main_fragment, state=null, class=android.widget.FrameLayout)
                  UiNode(, id=no_id, state=null, class=androidx.compose.ui.platform.ComposeView)
                    UiNode(, id=no_id, state=null, class=android.view.View)
                      UiNode(, id=no_id, state=null, class=android.view.View)
                        UiNode(, id=no_id, state=null, class=androidx.compose.ui.viewinterop.ViewFactoryHolder)
                          UiNode(, id=no_id, state=null, class=android.widget.FrameLayout)
                            UiNode(, id=no_id, state=null, class=android.widget.FrameLayout)
                              UiNode(, id=no_id, state=null, class=android.view.TextureView)
                              UiNode(, id=no_id, state=null, class=android.widget.FrameLayout)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(desc='Side Menu', id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(desc='', id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(text='$', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='1', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='9', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='4', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='.', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='1', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='3', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='This week', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.ScrollView)
                            UiNode(text='Schedule your dash for later', id=no_id, state=null, class=android.widget.TextView)
                            UiNode(text='This zone's full right now', id=no_id, state=null, class=android.widget.TextView)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(desc='Earnings Mode Switcher', id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='Time mode off', id=no_id, state=null, class=android.view.View)
                            UiNode(desc='Time mode on', id=no_id, state=null, class=android.view.View)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(desc='Safety tools', id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(text='Claim a spot', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(desc='', id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
              UiNode(, id=side_nav_container, state=null, class=android.widget.FrameLayout)
                UiNode(, id=no_id, state=null, class=android.widget.LinearLayout)
                  UiNode(, id=side_nav_compose_view, state=null, class=androidx.compose.ui.platform.ComposeView)
                    UiNode(, id=no_id, state=null, class=android.view.View)
                      UiNode(, id=no_id, state=null, class=android.view.View)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(text='Stephen T', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Home', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Schedule', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Account', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Ratings', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Earnings', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Promos', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Preferences', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Help', id=no_id, state=null, class=android.widget.TextView)
              UiNode(, id=side_nav_header_background, state=null, class=androidx.compose.ui.platform.ComposeView)
                UiNode(, id=no_id, state=null, class=android.view.View)
""".trimIndent()

    // Scenario 2: User has a scheduled dash and is able to start now.
    // Button says "Dash".
    private val startDashLog = """
UiNode(, id=no_id, state=null, class=android.widget.FrameLayout)
  UiNode(, id=no_id, state=null, class=android.widget.LinearLayout)
    UiNode(, id=no_id, state=null, class=android.widget.FrameLayout)
      UiNode(, id=action_bar_root, state=null, class=android.widget.LinearLayout)
        UiNode(, id=content, state=null, class=android.widget.FrameLayout)
          UiNode(, id=overlay_gesture_manager, state=null, class=android.widget.FrameLayout)
            UiNode(, id=root_constraint_layout, state=null, class=android.view.ViewGroup)
              UiNode(, id=side_nav_content_container, state=null, class=android.widget.FrameLayout)
                UiNode(, id=main_fragment, state=null, class=android.widget.FrameLayout)
                  UiNode(, id=no_id, state=null, class=androidx.compose.ui.platform.ComposeView)
                    UiNode(, id=no_id, state=null, class=android.view.View)
                      UiNode(, id=no_id, state=null, class=android.view.View)
                        UiNode(, id=no_id, state=null, class=androidx.compose.ui.viewinterop.ViewFactoryHolder)
                          UiNode(, id=no_id, state=null, class=android.widget.FrameLayout)
                            UiNode(, id=no_id, state=null, class=android.widget.FrameLayout)
                              UiNode(, id=no_id, state=null, class=android.view.TextureView)
                              UiNode(, id=no_id, state=null, class=android.widget.FrameLayout)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(desc='Side Menu', id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(desc='', id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(text='$', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='1', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='8', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='.', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='3', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='0', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='This week', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.ScrollView)
                            UiNode(text='Start your scheduled dash', id=no_id, state=null, class=android.widget.TextView)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(desc='Earnings Mode Switcher', id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='Time mode off', id=no_id, state=null, class=android.view.View)
                            UiNode(desc='Time mode on', id=no_id, state=null, class=android.view.View)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(desc='', id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(desc='Safety tools', id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(text='Dash', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(desc='', id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
              UiNode(, id=side_nav_container, state=null, class=android.widget.FrameLayout)
                UiNode(, id=no_id, state=null, class=android.widget.LinearLayout)
                  UiNode(, id=side_nav_compose_view, state=null, class=androidx.compose.ui.platform.ComposeView)
                    UiNode(, id=no_id, state=null, class=android.view.View)
                      UiNode(, id=no_id, state=null, class=android.view.View)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(text='Stephen T', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Home', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Schedule', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Account', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Ratings', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Earnings', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Promos', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Preferences', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Help', id=no_id, state=null, class=android.widget.TextView)
              UiNode(, id=side_nav_header_background, state=null, class=androidx.compose.ui.platform.ComposeView)
                UiNode(, id=no_id, state=null, class=android.view.View)
""".trimIndent()

    // Scenario 3: User hasn't scheduled but is able to dash now - zone busy or Platinum.
    // Button says "Dash".
    private val busyDashLog = """
UiNode(, id=no_id, state=null, class=android.widget.FrameLayout)
  UiNode(, id=no_id, state=null, class=android.widget.LinearLayout)
    UiNode(, id=no_id, state=null, class=android.widget.FrameLayout)
      UiNode(, id=action_bar_root, state=null, class=android.widget.LinearLayout)
        UiNode(, id=content, state=null, class=android.widget.FrameLayout)
          UiNode(, id=overlay_gesture_manager, state=null, class=android.widget.FrameLayout)
            UiNode(, id=root_constraint_layout, state=null, class=android.view.ViewGroup)
              UiNode(, id=side_nav_content_container, state=null, class=android.widget.FrameLayout)
                UiNode(, id=main_fragment, state=null, class=android.widget.FrameLayout)
                  UiNode(, id=no_id, state=null, class=androidx.compose.ui.platform.ComposeView)
                    UiNode(, id=no_id, state=null, class=android.view.View)
                      UiNode(, id=no_id, state=null, class=android.view.View)
                        UiNode(, id=no_id, state=null, class=androidx.compose.ui.viewinterop.ViewFactoryHolder)
                          UiNode(, id=no_id, state=null, class=android.widget.FrameLayout)
                            UiNode(, id=no_id, state=null, class=android.widget.FrameLayout)
                              UiNode(, id=no_id, state=null, class=android.view.TextureView)
                              UiNode(, id=no_id, state=null, class=android.widget.FrameLayout)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(desc='Side Menu', id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(desc='', id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(text='$', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='3', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='3', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='2', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='.', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='6', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='8', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='This week', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.ScrollView)
                            UiNode(text='Stay busy with lots of offers', id=no_id, state=null, class=android.widget.TextView)
                            UiNode(text='Avg. offer wait', id=no_id, state=null, class=android.widget.TextView)
                            UiNode(text='2 min', id=no_id, state=null, class=android.widget.TextView)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(desc='Earnings Mode Switcher', id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='Time mode off', id=no_id, state=null, class=android.view.View)
                            UiNode(desc='Time mode on', id=no_id, state=null, class=android.view.View)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(desc='Safety tools', id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(text='Dash', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(desc='', id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
              UiNode(, id=side_nav_container, state=null, class=android.widget.FrameLayout)
                UiNode(, id=no_id, state=null, class=android.widget.LinearLayout)
                  UiNode(, id=side_nav_compose_view, state=null, class=androidx.compose.ui.platform.ComposeView)
                    UiNode(, id=no_id, state=null, class=android.view.View)
                      UiNode(, id=no_id, state=null, class=android.view.View)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(text='Stephen T', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Home', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Schedule', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Account', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Ratings', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Earnings', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Promos', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Preferences', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Help', id=no_id, state=null, class=android.widget.TextView)
              UiNode(, id=side_nav_header_background, state=null, class=androidx.compose.ui.platform.ComposeView)
                UiNode(, id=no_id, state=null, class=android.view.View)
""".trimIndent()

    // Scenario 4: User is dashing and returns to the home screen.
    // DO NOT MATCH. User is online/dashing now.
    private val returnToDash = """
UiNode(, id=no_id, state=null, class=android.widget.FrameLayout)
  UiNode(, id=no_id, state=null, class=android.widget.LinearLayout)
    UiNode(, id=no_id, state=null, class=android.widget.FrameLayout)
      UiNode(, id=action_bar_root, state=null, class=android.widget.LinearLayout)
        UiNode(, id=content, state=null, class=android.widget.FrameLayout)
          UiNode(, id=overlay_gesture_manager, state=null, class=android.widget.FrameLayout)
            UiNode(, id=root_constraint_layout, state=null, class=android.view.ViewGroup)
              UiNode(, id=side_nav_content_container, state=null, class=android.widget.FrameLayout)
                UiNode(, id=main_fragment, state=null, class=android.widget.FrameLayout)
                  UiNode(, id=no_id, state=null, class=androidx.compose.ui.platform.ComposeView)
                    UiNode(, id=no_id, state=null, class=android.view.View)
                      UiNode(, id=no_id, state=null, class=android.view.View)
                        UiNode(, id=no_id, state=null, class=androidx.compose.ui.viewinterop.ViewFactoryHolder)
                          UiNode(, id=no_id, state=null, class=android.widget.FrameLayout)
                            UiNode(, id=no_id, state=null, class=android.widget.FrameLayout)
                              UiNode(, id=no_id, state=null, class=android.view.TextureView)
                              UiNode(, id=no_id, state=null, class=android.widget.FrameLayout)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(desc='Side Menu', id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(desc='', id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(text='$', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='0', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='.', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='0', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='0', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='This week', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.ScrollView)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(desc='', id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(desc='Safety tools', id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(text='Return to dash', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
              UiNode(, id=side_nav_container, state=null, class=android.widget.FrameLayout)
                UiNode(, id=no_id, state=null, class=android.widget.LinearLayout)
                  UiNode(, id=side_nav_compose_view, state=null, class=androidx.compose.ui.platform.ComposeView)
                    UiNode(, id=no_id, state=null, class=android.view.View)
                      UiNode(, id=no_id, state=null, class=android.view.View)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(text='Stephen T', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Home', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Schedule', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Account', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Ratings', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Earnings', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Promos', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Preferences', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='', id=no_id, state=null, class=android.view.View)
                            UiNode(text='Help', id=no_id, state=null, class=android.widget.TextView)
              UiNode(, id=side_nav_header_background, state=null, class=androidx.compose.ui.platform.ComposeView)
                UiNode(, id=no_id, state=null, class=android.view.View)
""".trimIndent()

    // Scenario 5: User is starting an Earn By Time dash.
    // Matches and returns "BY_TIME" mode.
    private val earnByTime = """
UiNode(, id=no_id, state=null, class=android.widget.FrameLayout)
  UiNode(, id=no_id, state=null, class=android.widget.LinearLayout)
    UiNode(, id=no_id, state=null, class=android.widget.FrameLayout)
      UiNode(, id=action_bar_root, state=null, class=android.widget.LinearLayout)
        UiNode(, id=content, state=null, class=android.widget.FrameLayout)
          UiNode(, id=overlay_gesture_manager, state=null, class=android.widget.FrameLayout)
            UiNode(, id=root_constraint_layout, state=null, class=android.view.ViewGroup)
              UiNode(, id=side_nav_content_container, state=null, class=android.widget.FrameLayout)
                UiNode(, id=main_fragment, state=null, class=android.widget.FrameLayout)
                  UiNode(, id=no_id, state=null, class=androidx.compose.ui.platform.ComposeView)
                    UiNode(, id=no_id, state=null, class=android.view.View)
                      UiNode(, id=no_id, state=null, class=android.view.View)
                        UiNode(, id=no_id, state=null, class=androidx.compose.ui.viewinterop.ViewFactoryHolder)
                          UiNode(, id=no_id, state=null, class=android.widget.FrameLayout)
                            UiNode(, id=no_id, state=null, class=android.widget.FrameLayout)
                              UiNode(, id=no_id, state=null, class=android.view.TextureView)
                              UiNode(, id=no_id, state=null, class=android.widget.FrameLayout)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(desc='Side Menu', id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(desc='', id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(text='$', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='3', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='3', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='2', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='.', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='6', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='8', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(text='This week', id=no_id, state=null, class=android.widget.TextView)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.ScrollView)
                            UiNode(text='It's peak pay time! Rate guaranteed', id=no_id, state=null, class=android.widget.TextView)
                            UiNode(text='+$4.00/hr until 7:29 PM', id=no_id, state=null, class=android.widget.TextView)
                            UiNode(text='Earning by time', id=no_id, state=null, class=android.widget.TextView)
                            UiNode(text='$15.75/active hr + tips', id=no_id, state=null, class=android.widget.TextView)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(desc='Earnings Mode Switcher', id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.view.View)
                            UiNode(desc='Time mode on', id=no_id, state=null, class=android.view.View)
                            UiNode(desc='Time mode on', id=no_id, state=null, class=android.view.View)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                          UiNode(desc='', id=no_id, state=null, class=android.view.View)
                          UiNode(, id=no_id, state=null, class=android.widget.Button)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                        UiNode(, id=no_id, state=null, class=android.view.View)
                        UiNode(, id=no_id, state=null, class=android.view.View)
""".trimIndent()

    @Test
    fun `matches Idle Map even when action button text is different (Zone Busy)`() {
        val root = LogToUiNodeParser.parseLog(zoneBusyLog)
        assertNotNull("Failed to parse log", root)

        val result = matcher.matches(root!!)

        assertNotNull("Should match Idle Map based on Structural Elements", result)
        assertTrue(result is ScreenInfo.IdleMap)

        val info = result as ScreenInfo.IdleMap
        assertEquals(Screen.MAIN_MAP_IDLE, info.screen)
    }

    @Test
    fun `matches Idle Map for scheduled dash`() {
        val root = LogToUiNodeParser.parseLog(startDashLog)
        assertNotNull("Failed to parse log", root)

        val result = matcher.matches(root!!)

        assertNotNull("Should match Idle Map based on Structural Elements", result)
        assertTrue(result is ScreenInfo.IdleMap)

        val info = result as ScreenInfo.IdleMap
        assertEquals(Screen.MAIN_MAP_IDLE, info.screen)
    }

    @Test
    fun `matches Idle Map for busy or platinum pre-dashing`() {
        val root = LogToUiNodeParser.parseLog(busyDashLog)
        assertNotNull("Failed to parse log", root)

        val result = matcher.matches(root!!)

        assertNotNull("Should match Idle Map based on Structural Elements", result)
        assertTrue(result is ScreenInfo.IdleMap)

        val info = result as ScreenInfo.IdleMap
        assertEquals(Screen.MAIN_MAP_IDLE, info.screen)
    }

    @Test
    fun `does not match Idle Map for return to dash`() {
        val root = LogToUiNodeParser.parseLog(returnToDash)
        assertNotNull("Failed to parse log", root)

        val result = matcher.matches(root!!)

        assertNull("Should NOT match Idle Map based on Structural Elements", result)
    }

    @Test
    fun `matches Idle Map for earn by time dash`() {
        val root = LogToUiNodeParser.parseLog(earnByTime)
        assertNotNull("Failed to parse log", root)

        val result = matcher.matches(root!!)

        assertNotNull("Should match Idle Map based on Structural Elements", result)
        assertTrue(result is ScreenInfo.IdleMap)

        val info = result as ScreenInfo.IdleMap
        assertEquals(Screen.MAIN_MAP_IDLE, info.screen)
        assertEquals(DashType.BY_TIME, info.dashType)
    }
}