package cloud.trotter.dashbuddy.statev2

import kotlinx.coroutines.CoroutineScope

/**
 * Interface for executing side effects generated by the State Machine.
 * Allows swapping implementation for Unit Tests/Simulation.
 */
interface EffectHandler {
    fun handle(effect: AppEffect, scope: CoroutineScope)
}